server:
  port: 10023

mybatis-plus:
  mapper-locations: ../resources/mapper/*.xml
  type-aliases-package: com.sharding.east.po



spring:
  shardingsphere:
    datasource:
      names: ds0,ds0slave,ds2,ds1,ds1slave,ds2slave
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_0?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456

      ds0slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_0_slave?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456

      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_2?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456

      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_1?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456

      ds1slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_1_slave?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456

      ds2slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_2_slave?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456

    sharding:
      # 分表配置
      tables:
        user:
          actualDataNodes: ds${0..1}.user_${0..2}

          #inline 表达式
          tableStrategy:
            inline:
              shardingColumn: id
              algorithmExpression: user_${id % 3}
          #生成id-->雪花策略
          keyGenerator:
            column: id
            type: SNOWFLAKE
            props:
              workid: 100

      #分库策略
      defaultDatabaseStrategy:
        inline:
          shardingColumn: id
          algorithmExpression: ds${id % 2}

      #广播表，每个数据节点都存在该表
      #broadcastTables: loudong

      #读写分离
      masterSlaveRules:
        ms_master0:
          masterDataSourceName: ds_0 #主节点需要配置主数据源真实数据库名
          slaveDataSourceNames:
            - ds0slave
            - ds2
          loadBalanceAlgorithmType: ROUND_ROBIN
        ms_master1:
          masterDataSourceName: ds_1
          slaveDataSourceNames:
            - ds1slave
            - ds2slave
          loadBalanceAlgorithmType: ROUND_ROBIN
    #打印sharding_jdbc sql
    props:
      sql.show: true




